      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.4.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          destination-github-username: 'UNEP'
          destination-repository-name: 'beat-plastic-pollution'
          user-email: xocasgv@gmail.com
          target-branch: main